// import libs
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ThemeProvider } from "@/providers/theme-provider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import { Toaster } from "sonner";

// import css
import "./globals.css";
import { Providers } from "./providers";
import { PageLoader } from "@/components/(general)/layouts/page-loader";
import { GoogleAnalytics } from "@next/third-parties/google";
import { FacebookPixelEvents } from "@/components/pixel-events";
import { Suspense } from "react";

import { GoogleTagManager } from "@next/third-parties/google";
import Script from "next/script";

const montserrat = Montserrat({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: { google: "i0ZneG0eia7xZg2Ly5GRuejfEBvKlBb0RJ7cPx1JtFA" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className={montserrat.className}>
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=AW-17039858517"
        strategy="afterInteractive"
      />
      <Script id="gtag-init" strategy="afterInteractive">
        {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'AW-17039858517');
  `}
      </Script>

      <Script
        src="https://www.googletagmanager.com/gtag/js?id=AW-17126219862"
        strategy="afterInteractive"
      />
      <Script id="gtag-init" strategy="afterInteractive">
        {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'AW-17126219862');
  `}
      </Script>

      <body className="ml:bg-white md:bg-bg-1 dark:bg-bg-dark-1">
        <PageLoader>
          <Providers>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange>
              {children}
              <Toaster position="top-right" richColors />
              <SpeedInsights />
              <Analytics />
            </ThemeProvider>
          </Providers>
        </PageLoader>
        <GoogleAnalytics gaId="G-EXZM4FE75Y" />
        <Suspense fallback={null}>
          <FacebookPixelEvents />
        </Suspense>
      </body>
    </html>
  );
}
