// import libs
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ThemeProvider } from "@/providers/theme-provider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import { Toaster } from "sonner";

// import css
import "./globals.css";
import { Providers } from "./providers";
import { PageLoader } from "@/components/(general)/layouts/page-loader";
import { GoogleAnalytics } from "@next/third-parties/google";
import { FacebookPixelEvents } from "@/components/pixel-events";
import { Suspense } from "react";

import { GoogleTagManager } from "@next/third-parties/google";
import Script from "next/script";

const montserrat = Montserrat({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: { google: "i0ZneG0eia7xZg2Ly5GRuejfEBvKlBb0RJ7cPx1JtFA" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className={montserrat.className}>
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=AW-17039858517"
        strategy="afterInteractive"
      />
      <Script id="gtag-init" strategy="afterInteractive">
        {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'AW-17039858517');
  `}
      </Script>

      <Script
        src="https://www.googletagmanager.com/gtag/js?id=AW-17126219862"
        strategy="afterInteractive"
      />
      <Script id="gtag-init-2" strategy="afterInteractive">
        {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'AW-17126219862');
  `}
      </Script>

      {/* Hàm report conversion */}
      <Script id="gtag-report-conversion" strategy="afterInteractive">
        {`
          function gtag_report_conversion(url) {
            var callback = function () {
              if (typeof(url) !== 'undefined') {
                window.location = url;
              }
            };
            gtag('event', 'conversion', {
              'send_to': 'AW-17039858517/blJzCM2o6b4aENW2nr0_',
              'value': 1.0,
              'currency': 'VND',
              'event_callback': callback
            });
            return false;
          }
          window.gtag_report_conversion = gtag_report_conversion; // expose function globally
        `}
      </Script>

      <Script id="facebook-pixel" strategy="afterInteractive">
        {`
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    
    fbq('init', '1900359257367063'); // existing pixel
    fbq('init', '2079727345770874'); // new pixel
    fbq('track', 'PageView');
  `}
      </Script>

      <noscript>
        <img
          height="1"
          width="1"
          style={{ display: "none" }}
          src="https://www.facebook.com/tr?id=1900359257367063&ev=PageView&noscript=1"
        />
        <img
          height="1"
          width="1"
          style={{ display: "none" }}
          src="https://www.facebook.com/tr?id=2079727345770874&ev=PageView&noscript=1"
        />
      </noscript>

      <body className="ml:bg-white md:bg-bg-1 dark:bg-bg-dark-1">
        <PageLoader>
          <Providers>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange>
              {children}
              <Toaster position="top-right" richColors />
              <SpeedInsights />
              <Analytics />
            </ThemeProvider>
          </Providers>
        </PageLoader>
        <GoogleAnalytics gaId="G-EXZM4FE75Y" />
        <Suspense fallback={null}>
          <FacebookPixelEvents />
        </Suspense>
      </body>
    </html>
  );
}
